app = "zenserver"
primary_region = "iad"

[mounts]
  source = "mt5_data"
  destination = "/root/.wine"

[http_service]
  internal_port = 8080
  force_https = false
  auto_stop_machines = false
  auto_start_machines = true

[[services]]
  internal_port = 5900
  protocol = "tcp"

  [[services.ports]]
    port = 5900

[[services]]
  internal_port = 8081
  protocol = "tcp"

  [[services.ports]]
    port = 8081
    handlers = ["http"]

[[services]]
  internal_port = 3389
  protocol = "tcp"

  [[services.ports]]
    port = 3389
